### ISSUE TITLE
Lsposed (lsposed manager)

### ISSUE THREAD

**Issue by koctik-2017** [pumPCin/gms-gp-gs-doze#1]
Здравствуйте, сделайте пожалуйста для менеджера lsposed другое имя пакета (например: org.lsposed.managers) так как текущее имя пакета находится в черных списках в некоторых банковских приложений.

**Comment by pumPCin** [comment]
> Здравствуйте, сделайте пожалуйста для менеджера lsposed другое имя пакета (например: org.lsposed.managers) так как текущее имя пакета находится в черных списках в некоторых банковских приложений.

Здравствуйте, напишите какой версией lsposed пользуетесь, и какое банковское приложение к примеру обнаруживает? я потестирую.

**Comment by koctik-2017** [comment]
Яндекс.Банк, версия lsposed 7274

**Comment by pumPCin** [comment]
> Яндекс.Банк, версия lsposed 7274

Т.е. Яндекс пей, имя пакета com.yandex.bank? Он у меня работает, в связке Magisk Delta, добавлен в MagiskHide, LSPosed сейчас использую из ветки LSPosed_mod, но там имя пакета тоже самое. Какими модулями lsposed пользуетесь?

**Comment by koctik-2017** [comment]
> > Яндекс.Банк, версия lsposed 7274
> 
> Т.е. Яндекс пей, имя пакета com.yandex.bank? Он у меня работает, в связке Magisk Delta, добавлен в MagiskHide, LSPosed сейчас использую из ветки LSPosed_mod, но там имя пакета тоже самое. Какими модулями lsposed пользуетесь?

Ну да, яндекс пэй, но дело в том что если он обнаруживает на устройстве приложение из черного списка то он начинает ругаться что устройство небезопасно и отключается бесконтактная оплата, сейчас я вхожу в lsposed с помощью уведомления (но мне более привычнее через приложение), я тоже использую Kitsune Mask в режиме SUList, Яндекс Пэй, Тинькофф (tinkoff pay), ПСБ работают, SberPay тоже работает, из модулей у меня Эмулятор NFC карт (NFC Card Emulator), UpdateLocker, CallRecording, LP, MirPay Security, NoStorageRestrict, Sberbank patcher.

**Comment by pumPCin** [comment]
> Ну да, яндекс пэй, но дело в том что...

Сделал менеджер с другим именем пакета в ветке lsposed_mod билд 7378 бранч try, можно ставить поверх, только включите перед этим в лспозд менеджере показ в уведомлениях, после того как обновите лспозд зайдите через уведомление в лспозд менеджер и в настройках создайте ярлык к лспозд менеджеру, т.к. старый ярлык будет не рабочим.
